M48
; DRILL file {KiCad 8.0.8} date 2025-02-12T04:53:45-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-12T04:53:45-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C2.500
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X121.1Y-86.934
T2
X76.6Y-74.434
X76.6Y-99.434
M30
